PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX operational: <http://opencaesar.io/example/vocabulary/operational#>

SELECT DISTINCT ?iri ?id ?name ?type
WHERE {

  VALUES ?componentType { operational:Objective operational:Mission }
  ?iri a ?componentType ;
    base:hasIdentifier ?id ;
    base:hasDescription ?name .

BIND(
    IF(CONTAINS(STR(?iri), "missions#"), "Subsystem",
      IF(CONTAINS(STR(?iri), "objectives#"), "Assembly", "")
    ) AS ?type
  )


 }
ORDER BY ?id