PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX operational: <http://opencaesar.io/example/vocabulary/operational#>

SELECT DISTINCT ?iri ?id ?name ?child_id ?child_name ?childiri ?type
WHERE {
    VALUES ?componentType { operational:Mission operational:Objective }
    VALUES ?relationType { operational:pursues base:aggregates}
	?iri a ?componentType ;
		base:hasCanonicalName ?name ;
  		?relationType ?childiri.
			OPTIONAL{
				?childiri base:hasCanonicalName ?child_name ;
					  base:hasIdentifier ?child_id ;
			}
  		  BIND(STRAFTER(STR(?relationType), "#") AS ?type) .

}
ORDER BY ?id ?child_id